BASE_REWARD_FACTOR: 64
BLS_WITHDRAWAL_PREFIX: 0x03
CHURN_LIMIT_QUOTIENT: 65536
DEPOSIT_CONTRACT_ADDRESS: 0x42cc0FcEB02015F145105Cf6f19F90e9BEa76558
DOMAIN_AGGREGATE_AND_PROOF: 0x06000000
DOMAIN_BEACON_ATTESTER: 0x01000000
DOMAIN_BEACON_PROPOSER: 0x00000000
DOMAIN_DEPOSIT: 0x03000000
DOMAIN_RANDAO: 0x02000000
DOMAIN_SELECTION_PROOF: 0x05000000
DOMAIN_VOLUNTARY_EXIT: 0x04000000
EFFECTIVE_BALANCE_INCREMENT: 1000000000
EJECTION_BALANCE: 16000000000
EPOCHS_PER_ETH1_VOTING_PERIOD: 32
EPOCHS_PER_HISTORICAL_VECTOR: 65536
EPOCHS_PER_RANDOM_SUBNET_SUBSCRIPTION: 256
EPOCHS_PER_SLASHINGS_VECTOR: 8192
ETH1_FOLLOW_DISTANCE: 1024
GENESIS_FORK_VERSION: 0x00000113
HISTORICAL_ROOTS_LIMIT: 16777216
HYSTERESIS_DOWNWARD_MULTIPLIER: 1
HYSTERESIS_QUOTIENT: 4
HYSTERESIS_UPWARD_MULTIPLIER: 5
INACTIVITY_PENALTY_QUOTIENT: 33554432
MAX_ATTESTATIONS: 128
MAX_ATTESTER_SLASHINGS: 1
MAX_COMMITTEES_PER_SLOT: 64
MAX_DEPOSITS: 16
MAX_EFFECTIVE_BALANCE: 32000000000
MAX_EPOCHS_PER_CROSSLINK: 64
MAX_PROPOSER_SLASHINGS: 16
MAX_SEED_LOOKAHEAD: 4
MAX_VALIDATORS_PER_COMMITTEE: 2048
MAX_VOLUNTARY_EXITS: 16
MIN_ATTESTATION_INCLUSION_DELAY: 1
MIN_DEPOSIT_AMOUNT: 1000000000
MIN_EPOCHS_TO_INACTIVITY_PENALTY: 4
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 6
MIN_GENESIS_DELAY: 86400
MIN_GENESIS_TIME: 1590483600
MIN_PER_EPOCH_CHURN_LIMIT: 4
MIN_SEED_LOOKAHEAD: 1
MIN_SLASHING_PENALTY_QUOTIENT: 32
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
PERSISTENT_COMMITTEE_PERIOD: 2048
PROPOSER_REWARD_QUOTIENT: 8
RANDOM_SUBNETS_PER_VALIDATOR: 1
SAFE_SLOTS_TO_UPDATE_JUSTIFIED: 8
SECONDS_PER_ETH1_BLOCK: 14
SECONDS_PER_SLOT: 12
SHUFFLE_ROUND_COUNT: 90
SLOTS_PER_EPOCH: 32
SLOTS_PER_HISTORICAL_ROOT: 8192
TARGET_AGGREGATORS_PER_COMMITTEE: 16
TARGET_COMMITTEE_SIZE: 128
VALIDATOR_REGISTRY_LIMIT: 1099511627776
WHISTLEBLOWER_REWARD_QUOTIENT: 512